### PR TITLE
RA-995: Simplify letting a user choose their own language

### PR DESCRIPTION
**Pull request by samuelmale**
Fixed simple bug that blocked form submission

Ticket : https://issues.openmrs.org/browse/RA-995

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you include the ticket link as advised here? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by samuelmale** [comment]
Its added sorry about that @dkayiwa

**Comment by samuelmale** [comment]
This was a completion of already merged PR. So this fixes a small bug @dkayiwa

**Comment by reubenvarghese1** [comment]
@dkayiwa @samuelmale Is this PR merge ready? This would help close https://issues.openmrs.org/browse/RA-995 and thereby let us include it as part of the 2.9.0 release

**Pull request merged**
